title: Chad Peltier # your name (or website title) here
logo: "/images/headshot_circle_small.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data | Defense Policy | Public Policy
  <br><br>
  Analyst in defense policy and OSINT analysis. #Rstats. Interested in data science for social good, public policy, and defense policy.
  <br><br>
  <a href="linkedin.com/in/chad-peltier-4aba855a">View my LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/cgpeltier">View my GitHub Profile</a>
  
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
