title: Chad Peltier # your name (or website title) here
logo: "/images/headshot_circle_smaller.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Defense policy + OSINT analyst. #Rstats. Interested in data science for social good, public policy, and defense policy.
  <br><br>
  <a href="linkedin.com/in/chad-peltier-4aba855a">View my LinkedIn Profile</a>
  
  
  
  
  
  
  
  
theme: jekyll-theme-minimal
